# Generated by Django 5.1.4 on 2024-12-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_admin_user_last_login_user_password'),
    ]

    operations = [
    ]
