# Generated by Django 5.1.4 on 2024-12-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20241211_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
