# Generated by Django 5.1.4 on 2024-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_experience_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
